### PR TITLE
fix(moderation): `UserId` instead of `Member` parameter & improve scheduling

### LINKED ISSUE #38: fix(moderation): Unable to parse UserIDs as users
## 🐞 Issue

ReVanced Bot is unable to use UserIDs as `user` arguments for people who are not found within the server

## ⚙ Reproduce

Attempt to ban someone who isn't in the server using a UserID 

## 🛠 Solution

Haven't looked into it

## ⚠ Additional context

Error message: 
`Cannot parse 1006256962842931221 as argument: User not found or unknown format
Please check the help menu for usage information`

### PR DESCRIPTION
**Pull request by Axelen123**
Fixes #38.

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
This change should be done on any moderation command necessary. That includes muting or unmuting for example.

**Comment by Axelen123** [comment]
> This change should be done on any moderation command necessary. That includes muting or unmuting for example.

mute/unmute are unaffected by the serenity bug, because it only occurs when the bot and target don't share a guild.

**Comment by oSumAtrIX** [comment]
Muting does not imply that the bot shares a guild with the user.

**Review by oSumAtrIX — APPROVED** [review]

File: src/utils/moderation.rs [hunk 1]
```diff
@@ -72,17 +72,25 @@ pub async fn mute_on_join(ctx: &serenity::Context, new_member: &mut serenity::Me
...
     let http = http.clone();
     let database = database.clone();
-    let mut member = member.clone();
+    // let mut member: Member = panic!("explod");
+    // let mut member = member.clone();
 
     tokio::spawn(async move {
         tokio::time::sleep(std::time::Duration::from_secs(mute_duration)).await;
+        let Some(mut member) = cache.member(guild_id, user_id) else {
+            // explod. they are not member lol
```
Comment (oSumAtrIX) [inline src/utils/moderation.rs:91]: Instead of spawning a thread, then waiting and then dismissing the assumption that the user is a member, this should be done before spawning a thread.
```suggestion
```

**Review by oSumAtrIX — CHANGES_REQUESTED** [review]
There is lots of messed up comments as well as formatting. Please fix them.

File: src/utils/moderation.rs (hunk 1 above)
Comment (Axelen123) [reply src/utils/moderation.rs]: We can't. The member might have left after the mute expires so we cannot really do it before we spawn the thread.

You did make me realize that the let-else was placed too early, but that has since been fixed.

**Review by oSumAtrIX — CHANGES_REQUESTED** [review]

**Review by oSumAtrIX — CHANGES_REQUESTED** [review]

File: src/commands/moderation.rs [hunk 2]
```diff
@@ -159,33 +159,36 @@ pub async fn unlock(ctx: Context<'_>) -> Result<(), Error> {
...
         pending_unmute.abort();
     }
 
     let author = ctx.author();
 
     let queue = queue_unmute_member(
-        &ctx.discord().http,
-        &data.database,
-        &member,
+        ctx.discord().http.clone(),
```
[the remark this answers is not in the document]
Comment (Axelen123) [reply src/commands/moderation.rs]: Thank you. I have implemented it now

File: src/commands/moderation.rs [hunk 3]
```diff
@@ -196,14 +199,15 @@ pub async fn unmute(
...
-    #[description = "The member to mute"] mut member: Member,
+    #[description = "The member to mute"] member: UserId,
     #[description = "Seconds"] seconds: Option<i64>,
     #[description = "Minutes"] minutes: Option<i64>,
     #[description = "Hours"] hours: Option<i64>,
     #[description = "Days"] days: Option<i64>,
     #[description = "Months"] months: Option<i64>,
     #[description = "The reason of the mute"] reason: String,
 ) -> Result<(), Error> {
+    let member = to_user!(member, ctx);
```
[the remark this answers is not in the document]
Comment (Axelen123) [reply src/commands/moderation.rs:209]: Yes, the parameter should no longer be called `member` since it works on any user now.
I do not necessarily think the returning early part makes any difference. Poise used to convert `UserId` to `User` for us before even calling the command function, but now we are just doing it explicitly to avoid the serenity bug until the fix for it gets released.

When the fix does get released, we can just remove the macro and make the functions accept `User` again (better autocomplete).

File: src/commands/moderation.rs [hunk 4]
```diff
@@ -155,55 +155,61 @@ pub async fn unlock(ctx: Context<'_>) -> Result<(), Error> {
...
 
     let author = ctx.author();
 
     let queue = queue_unmute_member(
-        &ctx.discord().http,
-        &data.database,
-        &member,
+        ctx.discord().clone(),
+        data.database.clone(),
+        ctx.guild_id().unwrap(),
```
Comment (oSumAtrIX) [inline src/commands/moderation.rs:181]: Why not pass `ctx` to `queue_unmute_member`?

File: src/commands/moderation.rs [hunk 5]
```diff
@@ -155,55 +155,61 @@ pub async fn unlock(ctx: Context<'_>) -> Result<(), Error> {
     .await
 }
 
-/// Unmute a member.
+/// Unmute a user.
 #[poise::command(slash_command)]
 pub async fn unmute(
     ctx: Context<'_>,
-    #[description = "The member to unmute"] member: Member,
+    #[description = "The user to unmute"] user: UserId,
```
Comment (oSumAtrIX) [inline src/commands/moderation.rs:162]: Technically we are unmuting a member because you can only mute or unmute members of a server even though `UserId` is used here. For that reason, comments and descriptions for slash commands should still refer to members even though internally they handle them as users.

**Review by oSumAtrIX — CHANGES_REQUESTED** [review]

File: src/commands/moderation.rs (hunk 4 above)
Comment (Axelen123) [reply src/commands/moderation.rs:181]: > Why not pass `ctx` to `queue_unmute_member`?

I am already passing a **serenity** context. I cannot make `queue_unmute_member` accept a **poise** context because we do not have access to that inside event handlers.

File: src/commands/moderation.rs (hunk 5 above)
Comment (Axelen123) [reply src/commands/moderation.rs]: Done

Comment (Axelen123) [reply src/commands/moderation.rs]: > Technically we are unmuting a member because you can only mute or unmute members of a server even though `UserId` is used here. For that reason, comments and descriptions for slash commands should still refer to members even though internally they handle them as users.

Keep in mind that with this PR, we will be able to update the database even if the user is not in the guild.
This is why I initially changed the parameter name to `user`.

File: src/commands/moderation.rs [hunk 6]
```diff
@@ -155,55 +155,61 @@ pub async fn unlock(ctx: Context<'_>) -> Result<(), Error> {
     .await
 }
 
-/// Unmute a member.
+/// Unmute a user.
```
Comment (oSumAtrIX) [inline src/commands/moderation.rs:158]: Here it should say member.

File: src/commands/moderation.rs [hunk 7]
```diff
@@ -155,55 +155,61 @@ pub async fn unlock(ctx: Context<'_>) -> Result<(), Error> {
...
         &ctx,
-        &ModerationKind::Unmute(member.user, author.clone(), queue),
+        &ModerationKind::Unmute(user, author.clone(), queue),
         configuration,
     )
     .await
 }
 
-/// Mute a member.
+/// Mute a user.
```
Comment (oSumAtrIX) [inline src/commands/moderation.rs:198]: Here it should say member.

File: src/commands/moderation.rs [hunk 8]
```diff
@@ -354,13 +331,18 @@ pub async fn mute(
 #[poise::command(slash_command)]
 pub async fn purge(
     ctx: Context<'_>,
-    #[description = "User"] user: Option<User>,
+    #[description = "User"] user: Option<UserId>,
```
Comment (oSumAtrIX) [inline src/commands/moderation.rs:334]: The description and comment above should say member here.

File: src/commands/moderation.rs [hunk 9]
```diff
@@ -471,16 +453,19 @@ pub async fn purge(
 #[poise::command(slash_command)]
 pub async fn ban(
     ctx: Context<'_>,
-    #[description = "User"] user: User,
+    #[description = "User"] user: UserId,
```
Comment (oSumAtrIX) [inline src/commands/moderation.rs:456]: The description and comment should say member here.

**Review by oSumAtrIX — CHANGES_REQUESTED** [review]

**Comment by Axelen123** [comment]
Not sure how I managed to miss that... Thank you

**Review by oSumAtrIX — APPROVED** [review]

**Comment by oSumAtrIX** [comment]
@Axelen123 lgtm.

**Comment by Axelen123** [comment]
good
